### PR TITLE
Fix pagebreaks in raw blocks

### LINKED ISSUE #2: Problems with page breaks
There are some issues with this package when there are page breaks.
Some examples below. Please let me know if you need more code from my document for debugging.

Thank you for the great package.

1.
image

2.
image

3.
image

### PR DESCRIPTION
**Pull request by PgBiel**
Fixes #2 by ensuring raw lines can't be broken apart by pagebreaks by default (which could lead to the line number being in the first page and the raw line content in another). I made it configurable in case breakable raw lines are needed for some reason.

I also updated the example document. Here's a comparison before and after this PR.

**Before:**
Raw block gets weirdly split across pages

**After:**
Raw block stays in one page properly

### CODE REVIEW

**Comment by max397574** [comment]
can't try this out right now but I'm just wondering
how will this affect codeblocks that are longer than a page?

**Comment by PgBiel** [comment]
It only affects raw.line, not raw itself. Otherwise pagebreaks wouldn't work

In other words, you'd only have a problem if you had a huge line that somehow occupied more than a page. Which is rather atypical case...

**Comment by max397574** [comment]
I'll try this out later to see if it fixes my issues

**Comment by max397574** [comment]
this did indeed fix all my issues

**Comment by PgBiel** [comment]
It was pointed out on Discord that this PR seems to cause a misalignment on line numbers. Needs investigation

**Comment by Dherse** [comment]
Since I am planning on fixing the way numbers are rendered anyway, I'll just merge this as-is.

Thanks ❤️

**Pull request merged**
